[project]
name = "credit-card-fraud-detection"
version = "0.1.0"
description = "A cloud-native, end-to-end real-time fraud detection system leveraging Apache Spark Streaming, Kafka, Cassandra, and Airflow, orchestrated entirely on Kubernetes"
requires-python = ">=3.11"
dependencies = []
